// MODULES //
import { useState, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";

// STYLES //
import styles from "../styles/pages/Apelabs.module.scss";

// COMPONENTS //
import Footer from "../components/Footer";
import Header from "../components/Header";

// Sections //
import HeroSection1 from "./sections/heroSection1";
import Section1 from "./sections/section1";
import Section3 from "./sections/section3";
import Section4 from "./sections/section4";
import Section5 from "./sections/section5";
import Section6 from "./sections/section6";

// PLUGINS //
import ScrollOut from "scroll-out";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

// IMAGES //
// import bg1 from "img/section1_bg.png";

//Registering ScrollTrigger
gsap.registerPlugin(ScrollTrigger);

/** Home Page */
export default function Apelabs() {
	// useEffect(() => {
	// 	let winWidth = window.innerWidth;
	// 	let winHeight = window.innerHeight;

	// 	gsap.to(".hero_wrap", {
	// 		xPercent: -100,
	// 		x: () => winWidth,
	// 		ease: "none",
	// 		scrollTrigger: {
	// 			trigger: ".hero_wrap",
	// 			start: "top top",
	// 			end: () => winWidth * 3,
	// 			scrub: true,
	// 			pin: true,
	// 			markers: true,
	// 		},
	// 	});
	// }, []);
	return (
		<div>
			<Head>
				<title>Apelabs</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className={`${styles.apelabs}`}>
				<HeroSection1 />
				<Section1 />
				<Section3 />
				<Section4 />
				<Section5 />
				<Section6 />
			</main>
			<Footer />
		</div>
	);
}
