// MODULES //
import { useState, useEffect } from "react";

// STYLES //
import styles from "../styles/pages/Apelabs.module.scss";

// COMPONENTS //
import Footer from "../components/Footer";
import Header from "../components/Header";
import Head from "next/head";
import Link from "next/link";

// Sections //

// PLUGINS //
import ScrollOut from "scroll-out";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

// IMAGES //
// import bg1 from "img/section1_bg.png";

//Registering ScrollTrigger
gsap.registerPlugin(ScrollTrigger);

/** Home Page */
export default function Apelabs() {
	useEffect(() => {
		ScrollOut({
			targets: ".animateDefault",
			// offset: 800,
			once: true,
		});
	}, []);
	return (
		<div>
			<Head>
				<title>Apeland</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className={`${styles.apelabs} ${styles.apeland}`}>
				<>
					<section
						className={`${styles.hero_wrap} hero_wrap`}
						style={{
							backgroundImage: `url("img/apeland_bg.jpg")`,
							backgroundSize: `100% 100%`,
							backgroundRepeat: `no-repeat`,
						}}
					>
						<div className={`${styles.heroSection1} ${styles.section_wrap} section`}>
							<div
								className={`${styles.section_content} even_section section_spacing`}
							>
								<div className={styles.hero_content}>
									<div className={styles.logo_img}>
										<img src="img/apeland.png" />
									</div>
									<h2 className={`${styles.hero_text} text_secondary text_600 text_md`}>
										JOIN A TRIBE
										<br /> AS OFFBEAT AS YOU
									</h2>
									<div className={styles.hero_img_apeland}>
										<img src="img/monkey1.png" />
									</div>
								</div>
							</div>
						</div>
						<div className={`${styles.heroSection3} section`}>
							<div className={`even_section section_spacing`}>
								<div className={styles.hero2_content}>
									<div className={`${styles.content_wrap} ${styles.gig}`}>
										<p className="text_reg text_500">
											COLLECT BANANAS &amp; WIN ENTRY FORM FOR
										</p>
										<img src="img/gig.png" className={styles.icon} />
										<p className="text_reg text_500">PROGRAM</p>
										<img src="img/chat_icon.png" className={styles.chat_icon} />
									</div>
								</div>
							</div>
						</div>
						<div className={`${styles.heroSection2} ${styles.section_wrap} section`}>
							<div className={`even_section section_spacing`}>
								<div className={styles.hero2_content}>
									<div className={styles.content_wrap}>
										<p className="text_reg text_700">GET ONE MORE CHANCE</p>
										<p className="text_lg text_700">SIMPLY SEND</p>
										<p className="text_reg text_500">
											to know more whatsapp #ApeItNow to 8108105600
										</p>
										<br />
										<p className="text_reg text_500">
											Increase your chance of gettingon invite by follwing us on
										</p>
										<img src="img/chat_icon.png" className={styles.chat_icon} />
										<div className={styles.social_icons}>
											<Link href="">
												<a>
													<img src="img/instagram.png" className={styles.icon} />
												</a>
											</Link>
											<Link href="">
												<a>
													<img src="img/facebook.png" className={styles.icon} />
												</a>
											</Link>
											<Link href="">
												<a>
													<img src="img/whatsapp.png" className={styles.icon} />
												</a>
											</Link>
										</div>
									</div>
								</div>
							</div>
						</div>
					</section>
				</>
			</main>
			<Footer />
		</div>
	);
}
