// MODULES //
import { useState, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";

// STYLES //
import styles from "../styles/pages/Apelabs.module.scss";

// COMPONENTS //
import Footer from "../components/Footer";
import Header from "../components/Header";

// Sections //
import Section1 from "./sections/section1";
import Section3 from "./sections/section3";
import Section4 from "./sections/section4";
import Section5 from "./sections/section5";
import Section6 from "./sections/section6";

// PLUGINS //
import ScrollOut from "scroll-out";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

// IMAGES //
// import bg1 from "img/section1_bg.png";

//Registering ScrollTrigger
gsap.registerPlugin(ScrollTrigger);

/** Home Page */
export default function Apelabs() {
	let innerWidth = 400;
	let innerHeight = 100;
	useEffect(() => {
		gsap.set(".massiveImage", {
			backgroundImage: `url(https://source.unsplash.com/random/${
				innerWidth * 3
			}x${innerHeight})`,
		});

		gsap.to(".massiveImage", {
			xPercent: -100,
			x: () => innerWidth,
			ease: "none",
			scrollTrigger: {
				trigger: ".massiveImage",
				start: "top top",
				end: () => innerWidth * 3,
				scrub: true,
				pin: true,
				invalidateOnRefresh: true,
				anticipatePin: 1,
			},
		});
	}, []);

	return (
		<div>
			<Head>
				<title>Apelabs</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className={`${styles.apelabs}`}>
				<Section1 />
				<Section3 />
				<Section4 />
				<Section5 />
				<Section6 />
			</main>
			<Footer />
		</div>
	);
}
