// MODULES //
import { useState, useEffect } from "react";

// STYLES //
import styles from "../styles/pages/Home.module.scss";

// COMPONENTS //
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Link from "next/link";

// PLUGINS //
// import ScrollOut from "scroll-out";

// IMAGES //
// import abtImage from "../public/img/home/how_about.png";

/** Home Page */
export default function Home() {
	return (
		<div>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className={`${styles.index_page}`}>
				<div className=""></div>
				<div className=""></div>
			</main>
			<Footer />
		</div>
	);
}
