// MODULES //
import { useState, useEffect } from "react";

// STYLES //
import styles from "../styles/pages/Home.module.scss";

// COMPONENTS //
import Footer from "../components/Footer";
import Header from "../components/Header";
import Head from "next/head";
import Link from "next/link";

// Sections //
import HeroSection1 from "./sections/heroSection1";
import Section1 from "./sections/section1";

// PLUGINS //
import ScrollOut from "scroll-out";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

// IMAGES //
// import abtImage from "../public/img/home/how_about.png";

/** Home Page */
export default function Home() {
	return (
		<div>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className={`${styles.index_page}`}>
				<div className={styles.index_wrap}>
					<div
						className={`${styles.section_wrap}`}
						style={{
							backgroundImage: `url("img/bg1.jpg")`,
						}}
					>
						<div className={styles.hero_content}>
							<div className={styles.logo_img}>
								<img src="img/apeland.png" />
							</div>
							<h2 className={`${styles.hero_text} text_secondary text_600 text_md`}>
								JOIN A TRIBE
								<br /> AS OFFBEAT AS YOU
							</h2>
							<div className={styles.hero_img}>
								<img src="img/monkey1.png" />
							</div>
							<Link href="apeland">
								<a className={`${styles.black_btn} black_btn text_md"`}>KNOW MORE</a>
							</Link>
						</div>
					</div>
					<div
						className={`${styles.section_wrap}`}
						style={{
							backgroundImage: `url("img/bg2.jpg")`,
						}}
					>
						<div className={styles.hero_content}>
							<div className={styles.logo_img}>
								<img src="img/apelabs.png" />
							</div>
							<h2 className={`${styles.hero_text} text_primary text_600 text_md`}>
								JOIN A TRIBE
								<br /> AS OFFBEAT AS YOU
							</h2>
							<div className={styles.hero_img}>
								<img src="img/mastmask.png" />
							</div>
							<Link href="apelabs">
								<a className={`${styles.black_btn} black_btn text_md"`}>KNOW MORE</a>
							</Link>
						</div>
					</div>
				</div>
			</main>
			{/* <Footer /> */}
		</div>
	);
}
